name: adaptive_flutter_layout
description: A production-ready Flutter package for layout adaptation across mobile, tablet, and desktop breakpoints with a clean declarative API.
version: 1.0.2
homepage: https://github.com/gikwegbu/adaptive_flutter_layout
repository: https://github.com/gikwegbu/adaptive_flutter_layout
issue_tracker: https://github.com/gikwegbu/adaptive_flutter_layout/issues
license: MIT

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

platforms:
  android:
  ios:
  web:
  macos:
  linux:
  windows:

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
